# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

lane :beta do
  build_app(scheme: “FastlaneProject”)
end

lane :match_gg do
  match(
  type: "development", 
 )
   match(
  type: "appstore", 
 ) 
end

lane :build_hockey do

  increment_build_number

  match(
   type: "adhoc"
  )


  gym(
    scheme: "FastlaneProject",
  )

  hockey(
    api_token: "05896f6fad794127ba03383fd68de45e",
  )
end










